name: Ergodotisi Job Monitor

on:
  schedule:
    - cron: '0 6,9,12,15,18 UTC'  # Run at 9:00, 12:00, 15:00, 18:00, and 21:00 Cyprus time (UTC+3)
  workflow_dispatch:  # Allow manual run

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests python-telegram-bot==13.15

      - name: Run the monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python ergodotisi_monitor.py
